AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Houdini Serverless stack - API Lambda + Worker Lambda + SQS + HTTP API

Parameters:
  LambdaRuntime:
    Type: String
    Default: python3.9
    Description: Python runtime for Lambdas

Resources:

  # SQS Queues
  RequestQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: houdini-request-queue

  ResponseQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: houdini-response-queue

  # IAM Role for Lambdas
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: houdini-lambda-execution-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: HoudiniSQSPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueUrl
                  - sqs:GetQueueAttributes
                Resource: 
                  - !GetAtt RequestQueue.Arn
                  - !GetAtt ResponseQueue.Arn

  # API Lambda
  ApiLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: houdini-api-lambda
      Runtime: !Ref LambdaRuntime
      Handler: app.handler
      CodeUri: src/api/
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          AWS_REGION: !Ref "AWS::Region"
          REQUEST_Q_URL: !GetAtt RequestQueue.QueueUrl
          RESPONSE_Q_URL: !GetAtt ResponseQueue.QueueUrl
    Metadata:
      BuildMethod: python3.9
      BuildArgs:
        - "--requirement ../../requirements.txt"

  # Worker Lambda
  WorkerLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: houdini-worker-lambda
      Runtime: !Ref LambdaRuntime
      Handler: handler.lambda_handler
      CodeUri: src/worker/
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          AWS_REGION: !Ref "AWS::Region"
          RESPONSE_Q_URL: !GetAtt ResponseQueue.QueueUrl
      Events:
        WorkerSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt RequestQueue.Arn
            BatchSize: 1
    Metadata:
      BuildMethod: python3.9
      BuildArgs:
        - "--requirement ../../requirements.txt"

  # HTTP API
  HoudiniHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: houdini-http-api
      CorsConfiguration:
        AllowMethods: ["GET", "POST", "OPTIONS"]
        AllowHeaders: ["*"]
        AllowOrigins: ["*"]

  # Connect API Lambda to HTTP API
  ApiLambdaIntegration:
    Type: AWS::Serverless::Api
    Properties:
      Name: houdini-http-api
      StageName: prod
      CorsConfiguration:
        AllowMethods: ["GET", "POST", "OPTIONS"]
        AllowHeaders: ["*"]
        AllowOrigins: ["*"]
      Target: !GetAtt ApiLambdaFunction.Arn

Outputs:
  ApiEndpoint:
    Description: "HTTP API endpoint"
    Value: !Sub "https://${HoudiniHttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
