AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Houdini Serverless stack - Single Worker Lambda with SQS + DLQ

Parameters:
  LambdaRuntime:
    Type: String
    Default: python3.9
    Description: Python runtime for Lambda

Resources:

  # SQS Queues
  RequestQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: houdini-request-queue

  ResponseQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: houdini-response-queue

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: houdini-dlq

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: houdini-lambda-execution-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: HoudiniSQSPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueUrl
                  - sqs:GetQueueAttributes
                Resource: 
                  - !GetAtt RequestQueue.Arn
                  - !GetAtt ResponseQueue.Arn
                  - !GetAtt DeadLetterQueue.Arn

  # Single Worker Lambda
  WorkerLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: houdini-worker-lambda
      Runtime: !Ref LambdaRuntime
      Handler: handler.lambda_handler
      CodeUri: src/worker/
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          REQUEST_Q_URL: !GetAtt RequestQueue.QueueUrl
          RESPONSE_Q_URL: !GetAtt ResponseQueue.QueueUrl
      Events:
        RequestSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt RequestQueue.Arn
            BatchSize: 1
            MaximumRetryAttempts: 2
            DeadLetterQueue:
              Type: SQS
              TargetArn: !GetAtt DeadLetterQueue.Arn
    Metadata:
      BuildMethod: python3.9
      BuildArgs:
        - "--requirement requirements.txt"

Outputs:
  RequestQueueUrl:
    Value: !Ref RequestQueue
  ResponseQueueUrl:
    Value: !Ref ResponseQueue
  DLQUrl:
    Value: !Ref DeadLetterQueue
