name: Deploy Houdini Serverless
on:
  push:
    branches: [ sqs_function ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: SAM Build
        run: sam build --use-container

      - name: SAM Deploy
        run: |
          sam deploy \
            --stack-name houdini-serverless \
            --capabilities CAPABILITY_NAMED_IAM \
            --region us-east-2 \
            --no-fail-on-empty-changeset \
            --s3-bucket ${{ secrets.S3_BUCKET }} \
            --no-confirm-changeset
